### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by DaWe35** [cattr-app/server-application#110]
https://demo.cattr.app/auth/login
"Data are flushing, please wait a minute and try again"
It is now broken for more than 2 days

At least please upload a video so I can decide if it worth to spend 2 days looking for nonexistent error messages.

**Comment by vermorag** [comment]
![image](https://github.com/cattr-app/server-application/assets/25276845/eb783b64-1a14-4d1c-beae-bba9db9286fe)
For now, the demo is working. Please, check
