### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute

### ISSUE THREAD

**Issue by yasirrose** [cattr-app/server-application#114]
Hi! 
I have installed a cattr server application on server. It works fine but when I reload on projects page or some other pages. it show message "Failed to find a valid digest in the 'integrity' attribute".  with computed SHA-256 integrity 'fuQkFmLBJIoCLlUWVi+t8q5hlRn/9S6yAeQuyPS2NjA='. The resource has been blocked.
Screenshot: https://i.imgur.com/MaZYiRC.png

**Comment by DanilShapilov** [comment]
Hi @yasirrose , recently we faced same problem. It was related to cloudflare.

As I remember we just disabled **proxied**
![image](https://github.com/cattr-app/server-application/assets/39529221/bfc0c816-ac0a-4a5a-839d-d5dfd0bb7275)

Or You can try to do what I've found here https://community.cloudflare.com/t/sri-integrity-check-for-scripts-fails-when-behind-cloudflare-proxy/247630
