### ISSUE TITLE
Installation failed with php artisan cattr:install

### ISSUE THREAD

**Issue by codewolf-in** [cattr-app/server-application#115]
I am trying to install cattr on ubuntu 22.04 by following the advanced installation guide. However, the installation failed on step 3 when we try to install from the cloned server-application.

$ composer install && php artisan cattr:install

 ERROR  Command "cattr:install" is not defined. Did you mean one of these?  

  ⇂ cattr:intervals:apps:clear-expired  
  ⇂ cattr:intervals:dedupe  
  ⇂ cattr:mail:test  
  ⇂ cattr:make:admin  
  ⇂ cattr:module:version  
  ⇂ cattr:register  
  ⇂ cattr:reset  
  ⇂ cattr:screenshots:rotate  
  ⇂ cattr:set:language  
  ⇂ cattr:set:timezone  
  ⇂ cattr:version  
  ⇂ migrate:install  
  ⇂ module:install  
  ⇂ octane:install  
  ⇂ telescope:install

**Comment by gurinder-mvt** [comment]
@codewolf-in  - just follow steps

1. clone repo
2. composer install
3. npm i
4. npm run prod
5. php artisan key:generate
6. php artisan migrate --seed --seeder=InitialSeeder
7. php artisan cattr:make:admin
8. changes in .env regarding db username & password
9. php artisan serve

**Comment by vermorag** [comment]
Yes. `cattr:install` has been removed from repo. You can use Docker installation now.
