### ISSUE TITLE
error HTTP 500 Internal Server Error after install

### ISSUE THREAD

**Issue by eniodefarias** [cattr-app/server-application#116]
after install, browser with error:

 Symfony Exception
 Symfony Docs
Exception  ViewException  ViewException
HTTP 500 Internal Server Error
Mix manifest not found at: /var/www/public_html/Cattr/server-application/public/mix-manifest.json (View: /var/www/public_html/Cattr/server-application/storage/framework/views/6788b9c6b822914857162f7531f38e8a.blade.php) (View: /var/www/public_html/Cattr/server-application/storage/framework/views/6788b9c6b822914857162f7531f38e8a.blade.php)

**Comment by gurinder-mvt** [comment]
@eniodefarias  - please run command `npm run prod`
