### ISSUE TITLE
installation guide needs an update

### ISSUE THREAD

**Issue by dariusdarwish** [cattr-app/server-application#117]
hi there, i've tried to install cattr with docker and fast installation, and then with manual installation and i got errors related to port of frontend 8089 and another errors in manual setup.

**Comment by lida2003** [comment]
lack of installation guide is a critical issue. It seems the code is un-maintained.

**Comment by vermorag** [comment]
I've written some notes about the new installation at https://github.com/orgs/cattr-app/discussions/163. Feel free to ask any questions there.
