### ISSUE TITLE
Getting `ERR_CONNECTION_REFUSED` with the Docker installation

### ISSUE THREAD

**Issue by sepsol** [cattr-app/server-application#118]
Followed [the official guide](https://docs.cattr.app/?_gl=1*l6kgfq*_gcl_au*NjAxODk4MTE2LjE2OTY4NzczMTk.*_ga*NzM1MTM0NzAwLjE2OTY4NzczMjE.*_ga_6WX6QRE7N9*MTY5Njg5NDQxNi4yLjEuMTY5Njg5NDQ1Ni4yMC4wLjA.#/en/getting-started/) but had no luck. Please advise!

**Comment by vermorag** [comment]
Please, check my installation notes for the new 4.0+ version and try to install it.
https://github.com/orgs/cattr-app/discussions/163
