### ISSUE TITLE
502 Bad Gateway nginx/1.18.0 (Ubuntu) After i install and run requirements

### ISSUE THREAD

**Issue by hbondoc** [cattr-app/server-application#120]
how to fix this issue 
502 Bad Gateway
nginx/1.18.0 (Ubuntu)

composer install
php artisan key:generate
yarn
php artisan migrate --seed --seeder=InitialSeeder
admin@cattr.app
password

I run all that no error.
but when I browse getting HTTP error.

**Comment by DanilShapilov** [comment]
Please provide logs from backend, also error message may be seen at network tab in devtools.

**Comment by hbondoc** [comment]
DO i need to down and extract the frontend and backend application along with server-application??? to work correctly, because the sample nginx config is different?

**Comment by DanilShapilov** [comment]
Sorry docs are outdated, one of possible solutions for Docker install https://github.com/cattr-app/server-application/issues/111#issuecomment-1630575155  

Or you can look inside .root-fs folder https://github.com/cattr-app/server-application/blob/main/.root-fs/etc/nginx/conf.d/app.conf
