### ISSUE TITLE
Cannot find the resource in the Yarn registry

### ISSUE THREAD

**Issue by RolandoContrerasGarcia** [cattr-app/server-application#162]
@cattr/gitlab-integration: Show an error that the resource cannot be found in the Yarn registry.

➤ YN0035: │ @cattr/gitlab-integration@npm:*: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@cattr%2fgitlab-integration

**Comment by vermorag** [comment]
It seems you're using yarn v1. Switch to yarn 3.5.0 as it required in project: https://github.com/cattr-app/server-application/blob/main/package.json#L106

**Comment by RolandoContrerasGarcia** [comment]
If I am using yarn 3.5.0

**Comment by vermorag** [comment]
Modern yarn uses new .yarnrc file: https://yarnpkg.com/migration/guide#update-your-configuration-to-the-new-settings
Cattr have that file: https://github.com/cattr-app/server-application/blob/main/.yarnrc.yml
So all `@cattr` packages will be fetched from amazingcat registry. According to your log - yarn trying to fetch from yarnpkg, that's wrong.
