### ISSUE TITLE
Contribute with the translation

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/server-application#53]
Hello, I would like to contribute to the project by translating the application into Spanish. How can I help you with the translation?

**Comment by aVyarvelsky** [comment]
Well... The translation isn't the strongest part of Cattr now. But basically, you should check:
https://github.com/cattr-app/server-application/tree/main/resources/lang (backend strings)
https://github.com/cattr-app/server-application/tree/main/resources/frontend/core/i18n/locales (main frontend)
And
https://github.com/cattr-app/server-application/tree/main/resources/frontend/core/modules/*/locales (locale for each module)

Pluralization rules: https://github.com/cattr-app/server-application/blob/main/resources/frontend/core/i18n/pluralizationRules.js

And basically https://github.com/cattr-app/server-application/blob/main/resources/frontend/core/i18n/index.js - here should be extra language.

FYI - I'm not working for Amazingcat anymore but will continue to help with this project in my free time, so PRs should be reviewed by one of their workers, I'm out of that process. Don't fear to mention me if you'll need any further help.

**Comment by lexcorp** [comment]
Ok @aVyarvelsky I have all files translated to spanish language, what do I have to do for cattr to recognize this language?

**Comment by aVyarvelsky** [comment]
On the backend, or frontend? Can you link a branch or your MR, please?

**Comment by lexcorp** [comment]
In both, but I don't know how to do what you say "link a branch or your MR"

**Comment by aVyarvelsky** [comment]
@lexcorp Can you show me what files have you changed?
