### ISSUE TITLE
Screenshot images don't show

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/server-application#54]
Screenshot image don't show:

![image](https://user-images.githubusercontent.com/5751288/234321781-703a7e23-1836-46fa-9065-6ec9cd6d1faa.png)

![image](https://user-images.githubusercontent.com/5751288/234322129-3ea06727-b831-480a-a8b9-00ce1fabda7f.png)

![image](https://user-images.githubusercontent.com/5751288/234322279-ff4c50cb-a19e-4d30-80f8-cc49aa40aca3.png)

![image](https://user-images.githubusercontent.com/5751288/234322805-13ab7d2a-3889-4f7b-b907-8b13493b74a3.png)

**Comment by lexcorp** [comment]
http://myip/api/time-intervals/1/thumb

{"status":401,"success":false,"error":{"code":"authorization.unauthorized","message":"Not authorized"}}

**Comment by aVyarvelsky** [comment]
I saw on another [issue](https://github.com/cattr-app/server-application/issues/59) you've posted, that you are missing gd extension, which is required for proper functioning. Install it and screenshots will be ok.

**Comment by lexcorp** [comment]
I confirm that after successfully installing the php-gd extension the images are displayed in cattr, although details are still displayed.

The images are not shown here
![image](https://github.com/cattr-app/server-application/assets/5751288/7f77eea2-95f8-4c87-a136-c20af33a60f3)

But if I click on a capture, I can view the image.
![image](https://github.com/cattr-app/server-application/assets/5751288/68a32950-168f-4881-8439-f2f56e49a484)
