### ISSUE TITLE
ERROR Command "cattr:install" is not defined

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/server-application#56]
ERROR  Command "cattr:install" is not defined. Did you mean one of these?  

  ⇂ cattr:intervals:apps:clear-expired  
  ⇂ cattr:intervals:dedupe  
  ⇂ cattr:mail:test  
  ⇂ cattr:make:admin  
  ⇂ cattr:module:version  
  ⇂ cattr:register  
  ⇂ cattr:reset  
  ⇂ cattr:screenshots:rotate  
  ⇂ cattr:set:language  
  ⇂ cattr:set:timezone  
  ⇂ cattr:version  
  ⇂ migrate:install  
  ⇂ module:install  
  ⇂ octane:install  
  ⇂ telescope:install

**Comment by thomcuddihy** [comment]
Hey mate, if you have a look at the README on the repo home page, it'll note that that command isn't part of the installation process anymore. The documentation website seems to be a bit behind

**Comment by thomcuddihy** [comment]
@lexcorp admittedly no, me neither... I ended up deploying Titra instead. That said, I'd still like to try Cattr at some point. I've got a watch on it, and hopefully it's just at an awkward stage of development right now.

**Comment by aVyarvelsky** [comment]
@lexcorp You can try to install Cattr on Docker or locally.
There is no install command because installation doesn't require any extra actions, that Laravel doesn't have already.

Please, paste the errors you've faced here, we still maintaining 4.0.0 release (it's a big major release with a lot of changes - that's why installation may be broken)

**Comment by lexcorp** [comment]
Hi @aVyarvelsky I'm install Cattr locally, this is my environment:

S.O = Rocky Linux 9
PHP = 8.2.6
MariaDB Server = 10.6.12
Nginx= nginx/1.20.1

I don't use docker

**Comment by lexcorp** [comment]
This is my nginx.conf, configuration file:

events {}
http{
map $http_upgrade $type {
  default "web";
  websocket "ws";
}

server {
  listen 80 default;
  server_name _;
  root /app/public;

  index index.php;

  location / { try_files /i-should-not-exist @$type; }

  location @web { try_files $uri $uri/ @octane; }

  location = /favicon.ico { access_log off; log_not_found off; }
  location = /robots.txt  { access_log off; log_not_found off; }

  location @ws {
    proxy_set_header Host $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_cache_bypass $http_upgrade;
    proxy_http_version 1.1;
    proxy_redirect off;

    proxy_pass http://127.0.0.1:6001;
  }
  location @octane {
    proxy_send_timeout 300;
    proxy_read_timeout 300;

    client_max_body_size 64M;

    proxy_set_header Host $http_host;
    proxy_set_header SERVER_PORT $server_port;
    proxy_set_header REMOTE_ADDR $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_pass http://127.0.0.1:8090$uri?$query_string;
  }
}
}

**Comment by lexcorp** [comment]
I will close this because I understand that the command installation option is for the old version and is no longer required in the new versions.
