### ISSUE TITLE
Cattr don't show styles

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/server-application#57]
When open url cattr shows without styles:

![image](https://user-images.githubusercontent.com/5751288/235370680-df44b32e-be8b-4368-aa04-e8f25062f34a.png)

**Comment by aVyarvelsky** [comment]
Have you run `yarn prod` or `yarn dev` before opening the site in the browser?

**Comment by lexcorp** [comment]
Hola @aVyarvelsky estoy ejecutando "yarn dev"

Adicionalmente te comento que estoy realizando la instalacion localmente, sin utilizar docker.

**Comment by lexcorp** [comment]
> Have you run `yarn prod` or `yarn dev` before opening the site in the browser?

What's the difference between yarn prod and yarn dev?

**Comment by aVyarvelsky** [comment]
`yarn prod` generate production-ready files. Without devtools, minimizes, obfuscates them and runs some optimizations (I hope it does so)

**Comment by lexcorp** [comment]
I'll close this because I think it was a mistake on my part, probably mix versions.
