### ISSUE TITLE
The POST method is not supported for route auth/login. Supported methods: GET, HEAD.

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/server-application#58]
When trying login to cattr I get this error:

Error

The POST method is not supported for route auth/login. Supported methods: GET, HEAD.

![image](https://user-images.githubusercontent.com/5751288/235370803-279b449f-e5c4-4651-8d70-60cccff92786.png)

**Comment by aVyarvelsky** [comment]
Have you tried action described in https://github.com/cattr-app/server-application/issues/57#issuecomment-1546268929?

**Comment by lexcorp** [comment]
I'll close this because I think it was a mistake on my part, probably mix versions.
