### ISSUE TITLE
php artisan cattr:make:admin error Email is incorrect or it was already registered

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/server-application#59]
When trying create an user admin I get this error:

php artisan cattr:make:admin

**Email is incorrect or it was already registered**

![image](https://user-images.githubusercontent.com/5751288/235370857-9276de17-ebf4-40dc-8592-c0ecce69172f.png)

**Comment by aVyarvelsky** [comment]
Have you run `php artisen seed` command? Without any parameters? It creates default admin. So when you try to create default admin once more - the command finishes with an error, that admin already exists.
Try using `php artisan cattr:reset` ещ куыуе вфефифыую

**Comment by lexcorp** [comment]
What is the default password for admin user?

**Comment by aVyarvelsky** [comment]
`password` or `admin` depending on cattr version. The older versions have `admin`.

Can we close that issue?

**Comment by lexcorp** [comment]
Thank you @aVyarvelsky, Yes close this please...
