### ISSUE TITLE
No application encryption key has been specified.

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/server-application#68]
I receive this message: No application encryption key has been specified.

![image](https://user-images.githubusercontent.com/5751288/236907331-ed1d0950-f817-49d3-8e62-eec683d92129.png)

I solve executing this:

php artisan key:generate

**Comment by aVyarvelsky** [comment]
You should do it by yourself when you install a fresh laravel app.
Check docs: https://laravel.com/docs/10.x/encryption#configuration
