### ISSUE TITLE
Cattr login 401 Unauthorized

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/server-application#73]
When try login, I get this message: We can't find the user with provided credentials

In web browser console I get this messages:

POST http://10.120.9.202/api/auth/login 401 (Unauthorized)

In network response I get:

{"status":401,"success":false,"error":{"code":"authorization.unauthorized","message":"Not authorized"}}

This is a video with details:

https://youtu.be/FWePH_S1Lig

**Comment by lexcorp** [comment]
Mother of God, I spent several hours breaking my head and it turns out that the default password for the admin user is "password" after entering this password I was able to enter cattr without problems.

**Comment by aVyarvelsky** [comment]
@DanilShapilov Pay attention - it seems not all mentioning of setup components has been removed.
At least, it is not clear to me why @lexcorp has those redirects. Setup pages have been deprecated as far as I remember.

**Comment by lexcorp** [comment]
@aVyarvelsky @DanilShapilov For this latest version of the cattr server, which version of the desktop application should I use? I have a problem trying to log in from the desktop application.

Desktop application version = 3.0.0-RC6

![image](https://github.com/cattr-app/server-application/assets/5751288/66e75199-bca8-4119-9e6e-023c7992d83d)

**Comment by lexcorp** [comment]
> @aVyarvelsky @DanilShapilov For this latest version of the cattr server, which version of the desktop application should I use? I have a problem trying to log in from the desktop application.
> 
> Desktop application version = 3.0.0-RC6
> 
> ![image](https://user-images.githubusercontent.com/5751288/238474139-66e75199-bca8-4119-9e6e-023c7992d83d.png)


I solve this by compiling and building the latest version of cattr desktop 3.0.0-RC10.
