### ISSUE TITLE
WebSocket connection failed

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/server-application#79]
I have several error messages in the browser console:

WebSocket connection to 'wss://10.120.9.202/app/cattr?protocol=7&client=js&version=8.0.2&flash=false' failed: 
app.js?id=35511ecac2c484a5b616bc18f449802a:2 

![image](https://github.com/cattr-app/server-application/assets/5751288/b7f1bc05-e612-4280-84b5-d642ec4fa3dc)

![image](https://github.com/cattr-app/server-application/assets/5751288/49288af5-2864-45f9-88f2-1e137c2358d4)

**Comment by aVyarvelsky** [comment]
You use unstable version, that have that functional in WIP status.
