### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/server-application#80]
I get this messages in web browser console:

Failed to load resource: the server responded with a status of 404 ()   www.gravatar.com/avatar/f9472aaaa08f26de48b7ed82c502a208?d=404:1

![image](https://github.com/cattr-app/server-application/assets/5751288/a321ea22-6083-4170-9e7a-7510501c7bd5)

**Comment by aVyarvelsky** [comment]
It's normal. If user don't have gravatar - it will be 404 error when loading that image.
